name: Leadership AdvantEdge
favicon: null
layout_spectrum: 0.76541
typography_spectrum: 0.6569829836953431
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#05416d'
    - '#fcc425'
    - '#dbe4ea'
    - '#6288a3'
  brandStrength: 0.8125
  lightness: 0.8107169680297375
  saturation: 0.3804881190881133
  rhythmicContrast: 0.10030377493239939
purpose: []
