name: Leadership AdvantEdge
favicon: null
layout_spectrum: 0.76541
typography_spectrum: 0.75309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#557e9d'
    - '#96afc1'
    - '#000055'
    - '#facf60'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.3804881190881133
  rhythmicContrast: 0.75
purpose: []
